gw_to_do_homepage:
    path:     /{page}
    defaults: { _controller: GWToDoBundle:Todo:index, page: 1 }
    requirements:
        page: \d*

gw_to_do_add:
    path:     /add/{project}
    defaults: { _controller: GWToDoBundle:Todo:add, project : null }
    requirements:
        project: \d*

gw_to_do_view:
    path:     /view/{id}
    defaults: { _controller: GWToDoBundle:Todo:view }
    requirements:
        id:   \d+

gw_to_do_edit:
    path:     /edit/{id}
    defaults: { _controller: GWToDoBundle:Todo:edit }
    requirements:
        id:   \d+

gw_to_do_delete:
    path:     /delete/{id}
    defaults: { _controller: GWToDoBundle:Todo:delete }
    requirements:
        id:   \d+
