gw_to_do_project_homepage:
    path:     /{page}
    defaults: { _controller: GWToDoBundle:Project:index, page: 1 }
    requirements:
        page: \d*

gw_to_do_project_add:
    path:     /add
    defaults: { _controller: GWToDoBundle:Project:add }

gw_to_do_project_edit:
    path:     /edit/{id}
    defaults: { _controller: GWToDoBundle:Project:edit }
    requirements:
        id:   \d+

gw_to_do_project_view:
    path:     /view/{id}
    defaults: { _controller: GWToDoBundle:Project:view }
    requirements:
        id:   \d+

gw_to_do_project_delete:
    path:     /delete/{id}
    defaults: { _controller: GWToDoBundle:Project:delete }
    requirements:
        id:   \d+
