services:
    gw_to_do.mostused:
        class: GW\ToDoBundle\Services\GWMostUsedWord
        tags:
            -  { name: twig.extension }
#    gw_to_do.example:
#        class: GW\ToDoBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
