<?php

namespace GW\ToDoBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
  public function viewAll($page, $nbPerPage)
  {
    $query = $this->getEntityManager()->createQueryBuilder('p')
      ->select('p')
      ->from('GWToDoBundle:Project', 'p')
      // ->orderBy('id', 'DESC')
      ->getQuery()
      ;
      $query
        ->setFirstResult(($page-1) * $nbPerPage)
        ->setMaxResults($nbPerPage)
      ;
      return new Paginator($query, true);

  }
}
