<?php

namespace GW\ToDoBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ToDoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToDoRepository extends \Doctrine\ORM\EntityRepository
{
  public function viewAll($page, $nbPerPage)
  {
    $query = $this->getEntityManager()->createQueryBuilder('t')
      ->select('t')
      ->from('GWToDoBundle:ToDo', 't')
      // ->orderBy('id', 'DESC')
      ->getQuery()
      ;
      $query
        ->setFirstResult(($page-1) * $nbPerPage)
        ->setMaxResults($nbPerPage)
      ;
      return new Paginator($query, true);

  }
}
